name: ci-build

on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: |
        msbuild /restore `
                /t:Build,Pack src/WinUI.TableView.csproj `
                /p:Configuration=Release `
                /p:Version=1.0.${{ github.run_number }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: artifacts/NuGet/Release
