name: ci-build

on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Build
      run: |
        msbuild /restore `
                /t:Build,Pack src/WinUI.TableView.csproj `
                /p:Configuration=Release `
                /p:Version=1.0.${{ github.run_number }}

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Run Tests
      run: |
        msbuild /restore `
                /t:Build tests/WinUI.TableView.Tests.csproj `
                /p:Platform=x64 `
                /p:Configuration=Release `
                /p:OutputPath=build

        vstest.console.exe tests\build\WinUI.TableView.Tests.build.appxrecipe --logger:"console;verbosity=normal" /InIsolation

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: artifacts/NuGet/Release
