name: ci-docs

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool update -g docfx

    - name: Add DocFX to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Build documentation
      run: docfx docs/docfx.json

    - uses: actions/upload-pages-artifact@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        path: artifacts/_site
